### ISSUE TITLE
Need new version : tx2gene.gencode.v47.csv

### ISSUE THREAD

**Issue by gbnitdgp** [bioconductor-source/tximport#1]
Presently, library(tximportData) contains tx2gene.gencode.v27.csv.
Can we have the tx2gene.gencode.v47.csv?
Is it at all required or available?

**Comment by lshep** [comment]
This is not currently the location to ask these types of questions.  Please ask on the support site support.bioconductor.org or reach out to the package maintainer that can be found on the package landing page https://bioconductor.org/packages/release/data/experiment/html/tximportData.html

**Comment by gbnitdgp** [comment]
Thanks.
